# Generated by Django 3.2.3 on 2021-05-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ifsc', models.CharField(max_length=150)),
                ('branch', models.CharField(max_length=150)),
                ('bank_id', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('bank_name', models.CharField(max_length=150)),
            ],
        ),
    ]
